import pandas as pd

INDEX='MachineIdentifier'
LABEL='HasDetections'

dtypes = {
          'MachineIdentifier':                                    'category',
          'ProductName':                                          'category',
          'EngineVersion':                                        'category',
          'AppVersion':                                           'category',
          'AvSigVersion':                                         'category',
          'IsBeta':                                               'Int8',
          'RtpStateBitfield':                                     'float32',
          'IsSxsPassiveMode':                                     'Int8',
          'DefaultBrowsersIdentifier':                            'float32',
          'AVProductStatesIdentifier':                            'float32',
          'AVProductsInstalled':                                  'float32',
          'AVProductsEnabled':                                    'float32',
          'HasTpm':                                               'Int8',
          'CountryIdentifier':                                    'int32',
          'CityIdentifier':                                       'float32',
          'OrganizationIdentifier':                               'float32',
          'GeoNameIdentifier':                                    'float32',
          'LocaleEnglishNameIdentifier':                          'int32',
          'Platform':                                             'category',
          'Processor':                                            'category',
          'OsVer':                                                'category',
          'OsBuild':                                              'int16',
          'OsSuite':                                              'int16',
          'OsPlatformSubRelease':                                 'category',
          'OsBuildLab':                                           'category',
          'SkuEdition':                                           'category',
          'IsProtected':                                          'float32',
          'AutoSampleOptIn':                                      'Int8',
          'PuaMode':                                              'category',
          'SMode':                                                'float32',
          'IeVerIdentifier':                                      'float32',
          'SmartScreen':                                          'category',
          'Firewall':                                             'float32',
          'UacLuaenable':                                         'float64',
          'Census_MDC2FormFactor':                                'category',
          'Census_DeviceFamily':                                  'category',
          'Census_OEMNameIdentifier':                             'float32',
          'Census_OEMModelIdentifier':                            'float32',
          'Census_ProcessorCoreCount':                            'float32',
          'Census_ProcessorManufacturerIdentifier':               'float32',
          'Census_ProcessorModelIdentifier':                      'float32',
          'Census_ProcessorClass':                                'category',
          'Census_PrimaryDiskTotalCapacity':                      'float32',
          'Census_PrimaryDiskTypeName':                           'category',
          'Census_SystemVolumeTotalCapacity':                     'float32',
          'Census_HasOpticalDiskDrive':                           'Int8',
          'Census_TotalPhysicalRAM':                              'float32',
          'Census_ChassisTypeName':                               'category',
          'Census_InternalPrimaryDiagonalDisplaySizeInInches':    'float32',
          'Census_InternalPrimaryDisplayResolutionHorizontal':    'float32',
          'Census_InternalPrimaryDisplayResolutionVertical':      'float32',
          'Census_PowerPlatformRoleName':                         'category',
          'Census_InternalBatteryType':                           'category',
          'Census_InternalBatteryNumberOfCharges':                'float32',
          'Census_OSVersion':                                     'category',
          'Census_OSArchitecture':                                'category',
          'Census_OSBranch':                                      'category',
          'Census_OSBuildNumber':                                 'int32',
          'Census_OSBuildRevision':                               'int32',
          'Census_OSEdition':                                     'category',
          'Census_OSSkuName':                                     'category',
          'Census_OSInstallTypeName':                             'category',
          'Census_OSInstallLanguageIdentifier':                   'float32',
          'Census_OSUILocaleIdentifier':                          'int32',
          'Census_OSWUAutoUpdateOptionsName':                     'category',
          'Census_IsPortableOperatingSystem':                     'Int8',
          'Census_GenuineStateName':                              'category',
          'Census_ActivationChannel':                             'category',
          'Census_IsFlightingInternal':                           'float32',
          'Census_IsFlightsDisabled':                             'float32',
          'Census_FlightRing':                                    'category',
          'Census_ThresholdOptIn':                                'float32',
          'Census_FirmwareManufacturerIdentifier':                'float32',
          'Census_FirmwareVersionIdentifier':                     'float32',
          'Census_IsSecureBootEnabled':                           'Int8',
          'Census_IsWIMBootEnabled':                              'float32',
          'Census_IsVirtualDevice':                               'float32',
          'Census_IsTouchEnabled':                                'Int8',
          'Census_IsPenCapable':                                  'Int8',
          'Census_IsAlwaysOnAlwaysConnectedCapable':              'float32',
          'Wdft_IsGamer':                                         'float32',
          'Wdft_RegionIdentifier':                                'float32',
          'HasDetections':                                        'Int8'
    }

def load(filepath='train.csv', nrows=1000000):
    print("[LOADER] Loading training data")

    df = pd.read_csv(filepath, dtype=dtypes, nrows=nrows)
    df.drop(columns=INDEX, axis=1, inplace=True)                      # ignore machine identifier
    Y = df.pop(LABEL)

    return df, Y